config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticated :admin, ->(admin) { admin.super_admin? } do
    mount Sidekiq::Web, at: 'admins/sidekiq'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    confirmations: 'admins/confirmations',
    invitations: 'admins/invitations'
  }

  devise_for :candidates, path: 'candidates', controllers: {
    sessions: 'candidates/sessions',
    registrations: 'candidates/registrations',
    passwords: 'candidates/passwords',
    confirmations: 'candidates/confirmations',
    masquerades: 'admins/masquerades'
  }

  devise_for :recruiters, path: 'recruiters', controllers: {
    sessions: 'recruiters/sessions',
    registrations: 'recruiters/registrations',
    passwords: 'recruiters/passwords',
    confirmations: 'recruiters/confirmations',
    masquerades: 'admins/masquerades'
  }

  devise_scope :admin do
    post 'admins/invitations/resend', to: 'admins/invitations#resend',
                                      as: :resend_admins_invitations,
                                      constraints: { format: :json }
  end

  devise_scope :candidate do
    post '/auth/github' => 'omniauth_callbacks#passthru', as: :candidate_github_omniauth_authorize
    post '/auth/google_oauth2' => 'omniauth_callbacks#passthru', as: :candidate_google_oauth2_omniauth_authorize
    post '/auth/twitter' => 'omniauth_callbacks#passthru', as: :candidate_twitter_omniauth_authorize
  end

  devise_scope :recruiter do
    post '/auth/github' => 'omniauth_callbacks#passthru', as: :recruiter_github_omniauth_authorize
    post '/auth/google_oauth2' => 'omniauth_callbacks#passthru', as: :recruiter_google_oauth2_omniauth_authorize
    post '/auth/twitter' => 'omniauth_callbacks#passthru', as: :recruiter_twitter_omniauth_authorize
  end

  get '/auth/github/callback' => 'omniauth_callbacks#github', as: :github_omniauth_callback
  get '/auth/google_oauth2/callback' => 'omniauth_callbacks#google_oauth2', as: :google_oauth2_omniauth_callback
  get '/auth/twitter/callback' => 'omniauth_callbacks#twitter', as: :twitter_omniauth_callback

  authenticated :admin do
    root 'admins/dashboard#show', as: :admins_authenticated_root
  end

  authenticated :candidate do
    root 'candidates/dashboard#show', as: :candidates_authenticated_root
  end

  authenticated :recruiter do
    root 'recruiters/dashboard#show', as: :recruiters_authenticated_root
  end

  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/about', to: 'pages#home'
  get '/cotizacion', to: 'pages#home'
  post '/contact_form', to: 'contact_form#create'

  namespace :admins do
    get 'dashboard/show'

    resources :admins, only: %i[index]
    resources :candidates, only: %i[index]
    resources :recruiters, only: %i[index]
    resources :payments, only: %i[index]

    resources :invitation_requests, only: %i[index new create] do
      scope constraints: { format: :json } do
        member do
          post :dismiss
          post :ban
        end
      end
    end

    get 'enable_otp', to: 'admins#enable_otp'
    post 'enable_otp_verify', to: 'admins#enable_otp_verify'

    get 'disable_otp', to: 'admins#disable_otp'
    post 'disable_otp_verify', to: 'admins#disable_otp_verify'
  end

  namespace :candidates do
    get 'dashboard/show'

    resources :subscriptions, only: %i[index create] do
      get :prices, on: :collection
      get :billing_portal, on: :collection
    end

    resource :my_resume, only: %i[show update], controller: :my_resume
    resources :education_items, only: %i[create destroy]
    resources :work_experience_items, only: %i[create destroy]
    resources :skill_items, only: %i[create destroy]
    resources :reference_items, only: %i[create destroy]
    resources :external_link_items, only: %i[create destroy]

    resources :job_postings, only: %i[index show]
    resources :postulations, only: :create
  end

  namespace :recruiters do
    get 'dashboard/show'

    resources :job_postings do
      resources :postulations, only: [] do
        post :approve
        post :reject
      end
    end
    resources :candidates, only: %i[index show]
    resources :resumes, only: %i[show]
  end

  resources :stripe_webhooks, only: [:create]
end

app/views/layouts/shared/_dashboard.html.erb
<%# TODO: Move the whole dashboard to a React component %>
<%# TODO: This will allow us to use React Router for the all the pages %>
<%# TODO: We can also use React Router for the sidebar and navbar %>

<div id="dashboard-container" class="bg-primary">
  <div class="sticky-top">
    <% if candidate_masquerade? || recruiter_masquerade? %>
      <div id="back-masquerade" class="bg-danger py-1 text-center sticky-top">
        <%= link_to t('dashboard.return_to_admin_dashboard'), back_masquerade_path(user), class: 'bg-light btn px-2 py-0 text-danger text-decoration-none' %>
      </div>
    <% end %>
  </div>


  <div class="d-flex min-vh-100">
    <%= render 'layouts/shared/sidebar_container', user: user %>

    <div id="dashboard-content" class="w-100">
      <%= render 'layouts/shared/navbar', user: user %>

      <main id="dashboard-main-content" class="py-3 bg-light">
        <div class="container-fluid">
          <div class="bg-white mb-3 p-3 shadow rounded-1">
            <%= yield :top_section %>
          </div>

          <div class="bg-white p-3 shadow rounded-1">
            <%= yield %>
          </div>
        </div>
      </main>

      <%= render 'layouts/shared/footer' %>
    </div>
  </div>
</div>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <% if value.kind_of?(Array) %>
    <% value.each do |message| %>
      <div
        class="alert alert-dismissible fade show mb-0 rounded-0 border-0 <%= key == 'notice' ? 'alert-success' : 'alert-danger' %>"
        role="alert"
      >
        <%= message.html_safe %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  <% else %>
    <div
      class="alert alert-dismissible fade show mb-0 rounded-0 border-0 <%= key == 'notice' ? 'alert-success' : 'alert-danger' %>"
      role="alert"
    >
      <%= value.html_safe %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/layouts/shared/_footer.html.erb
  <section id="footer" class="bg-light">
    <div class="text-center border-top mx-3">
      <%= link_to home_path, class: 'btn btn-link col-6 col-sm-3 col-md-2 px-4 py-2' do %>
        <%= image_tag 'logos/dark.png', class: 'img-fluid logo' %>
      <% end %>
    </div>
  </section>

app/views/layouts/shared/_head.html.erb
<head>
  <%= favicon_link_tag asset_path('favicons/favicon.png') %>
  <title>Simplest Resumes</title>
  <meta name="description" content="Make jobs simple">
  <meta name="keywords" content="jobs offers recruitment">

  <link rel="canonical" href="https://simplestresumes.com/" />

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true %>

  <%# Next was the solution to an issue with the mission accordion styles %>
  <link href="https://fonts.cdnfonts.com/css/fontawesome" rel="stylesheet">

  <meta property="og:title" content="Simplest Resumes">
  <meta property="og:description" content="Keep resumes simple!">
  <meta property="og:image" itemprop="image" content="https://simplestresumes.com/primary.png">
  <meta property="og:url" content="https://simplestresumes.com">
  <meta property="og:type" content="website">

  <meta name="twitter:title" content="Simplest Resumes">
  <meta name="twitter:description" content="Keep resumes simple!">
  <meta name="twitter:image" content="https://simplestresumes.com/primary.png">
  <meta property="twitter:url" content="https://simplestresumes.com">
  <meta name="twitter:card" content="summary_large_image">
  <meta property="twitter:domain" content="simplestresumes.com">
</head>

app/views/layouts/shared/_navbar.html.erb
<%= javascript_tag do %>
  var navbarConfig = function() {
    return (
      <%= { user_type: current_user.class.name.downcase }.to_json.html_safe %>
    )
  }
<% end %>

<%= content_tag(:nav, '', id: 'dashboard-navbar', data: {
  controller: 'navbar'
}) %>

app/views/layouts/shared/_sidebar_container.html.erb
<div id="sidebar-mobile" class="offcanvas offcanvas-start d-lg-none bg-primary" tabindex="-1" aria-labelledby="sidebar">
  <div class="h-100">
    <div class="p-4">
      <%= link_to root_path do %>
        <%= image_tag 'logos/light.png', class: 'mw-100' %>
      <% end %>
    </div>

    <ul class="sidebar-nav p-0">
      <%= render "layouts/#{user.class.name.downcase.pluralize}/sidebar", user: user %>
    </ul>
  </div>
</div>

<div id="sidebar" class="d-none d-lg-inline-block">
  <div class="h-100">
    <div class="p-4">
      <%= link_to root_path do %>
        <%= image_tag 'logos/light.png', class: 'mw-100' %>
      <% end %>
    </div>

    <ul class="sidebar-nav p-0">
      <%= render "layouts/#{user.class.name.downcase.pluralize}/sidebar", user: user %>
    </ul>
  </div>
</div>