config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticated :admin, ->(admin) { admin.super_admin? } do
    mount Sidekiq::Web, at: 'admins/sidekiq'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    confirmations: 'admins/confirmations',
    invitations: 'admins/invitations'
  }

  devise_for :candidates, path: 'candidates', controllers: {
    sessions: 'candidates/sessions',
    registrations: 'candidates/registrations',
    passwords: 'candidates/passwords',
    confirmations: 'candidates/confirmations',
    masquerades: 'admins/masquerades'
  }

  devise_for :recruiters, path: 'recruiters', controllers: {
    sessions: 'recruiters/sessions',
    registrations: 'recruiters/registrations',
    passwords: 'recruiters/passwords',
    confirmations: 'recruiters/confirmations',
    masquerades: 'admins/masquerades'
  }

  devise_scope :admin do
    post 'admins/invitations/resend', to: 'admins/invitations#resend',
                                      as: :resend_admins_invitations,
                                      constraints: { format: :json }
  end

  devise_scope :candidate do
    post '/auth/github' => 'omniauth_callbacks#passthru', as: :candidate_github_omniauth_authorize
    post '/auth/google_oauth2' => 'omniauth_callbacks#passthru', as: :candidate_google_oauth2_omniauth_authorize
    post '/auth/twitter' => 'omniauth_callbacks#passthru', as: :candidate_twitter_omniauth_authorize
  end

  devise_scope :recruiter do
    post '/auth/github' => 'omniauth_callbacks#passthru', as: :recruiter_github_omniauth_authorize
    post '/auth/google_oauth2' => 'omniauth_callbacks#passthru', as: :recruiter_google_oauth2_omniauth_authorize
    post '/auth/twitter' => 'omniauth_callbacks#passthru', as: :recruiter_twitter_omniauth_authorize
  end

  get '/auth/github/callback' => 'omniauth_callbacks#github', as: :github_omniauth_callback
  get '/auth/google_oauth2/callback' => 'omniauth_callbacks#google_oauth2', as: :google_oauth2_omniauth_callback
  get '/auth/twitter/callback' => 'omniauth_callbacks#twitter', as: :twitter_omniauth_callback

  authenticated :admin do
    root 'admins/dashboard#show', as: :admins_authenticated_root
  end

  authenticated :candidate do
    root 'candidates/dashboard#show', as: :candidates_authenticated_root
  end

  authenticated :recruiter do
    root 'recruiters/dashboard#show', as: :recruiters_authenticated_root
  end

  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/about', to: 'pages#home'
  get '/cotizacion', to: 'pages#home'
  post '/contact_form', to: 'contact_form#create'

  namespace :admins do
    get 'dashboard/show'

    resources :admins, only: %i[index]
    resources :candidates, only: %i[index]
    resources :recruiters, only: %i[index]
    resources :payments, only: %i[index]

    resources :invitation_requests, only: %i[index new create] do
      scope constraints: { format: :json } do
        member do
          post :dismiss
          post :ban
        end
      end
    end

    get 'enable_otp', to: 'admins#enable_otp'
    post 'enable_otp_verify', to: 'admins#enable_otp_verify'

    get 'disable_otp', to: 'admins#disable_otp'
    post 'disable_otp_verify', to: 'admins#disable_otp_verify'
  end

  namespace :candidates do
    get 'dashboard/show'

    resources :subscriptions, only: %i[index create] do
      get :prices, on: :collection
      get :billing_portal, on: :collection
    end

    resource :my_resume, only: %i[show update], controller: :my_resume
    resources :education_items, only: %i[create destroy]
    resources :work_experience_items, only: %i[create destroy]
    resources :skill_items, only: %i[create destroy]
    resources :reference_items, only: %i[create destroy]
    resources :external_link_items, only: %i[create destroy]

    resources :job_postings, only: %i[index show]
    resources :postulations, only: :create
  end

  namespace :recruiters do
    get 'dashboard/show'

    resources :job_postings do
      resources :postulations, only: [] do
        post :approve
        post :reject
      end
    end
    resources :candidates, only: %i[index show]
    resources :resumes, only: %i[show]
  end

  resources :stripe_webhooks, only: [:create]
end

app/views/layouts/admins/_sidebar.html.erb
<li>
  <a href="/" class="sidebar-link text-light px-4 py-2 collapsed" data-bs-toggle="collapse" data-bs-target="#users-dropdown" aria-expanded="false" aria-controls="users-dropdown">
    <i class="bi bi-person-fill pe-2 pe-2"></i>
    <%= t('dashboard.users') %>
  </a>

  <ul id="users-dropdown" class="sidebar-dropdown list-unstyled collapse <%= active_sidebar_option?({ 'admins/admins' => ['index'], 'admins/candidates' => ['index'], 'admins/recruiters' => ['index'] }) ? 'show' : '' %>" data-bs-parent="#sidebar">
    <li>
      <%= link_to t('dashboard.admins'), admins_admins_path, class: "sidebar-link text-light px-4 py-2 #{active_sidebar_option?({ 'admins/admins' => ['index'] }) ? 'bg-primary-dark' : ''}" %>
    </li>
    <li>
      <%= link_to t('dashboard.candidates'), admins_candidates_path, class: "sidebar-link text-light px-4 py-2 #{active_sidebar_option?({ 'admins/candidates' => ['index'] }) ? 'bg-primary-dark' : ''}" %>
    </li>
    <li>
      <%= link_to t('dashboard.recruiters'), admins_recruiters_path, class: "sidebar-link text-light px-4 py-2 #{active_sidebar_option?({ 'admins/recruiters' => ['index'] }) ? 'bg-primary-dark' : ''}" %>
    </li>
  </ul>
</li>

<% if policy([:admins, :invitation]).new? %>
  <li>
    <a href="/" class="sidebar-link text-light px-4 py-2 collapsed" data-bs-toggle="collapse" data-bs-target="#invitations-dropdown" aria-expanded="false" aria-controls="invitations-dropdown">
      <i class="bi bi-person-fill-add pe-2 pe-2"></i>
      <%= t('dashboard.invitations') %>
    </a>

    <ul id="invitations-dropdown" class="sidebar-dropdown list-unstyled collapse <%= active_sidebar_option?({ 'admins/invitations' => ['new'], 'admins/invitation_requests' => ['index'] }) ? 'show' : '' %>" data-bs-parent="#sidebar">
      <li>
        <%= link_to t('dashboard.send_invitation'), new_admin_invitation_path, class: "sidebar-link text-light px-4 py-2 #{active_sidebar_option?({ 'admins/invitations' => ['new'] }) ? 'bg-primary-dark' : ''}" %>
      </li>
      <li>
        <%= link_to t('dashboard.requests'), admins_invitation_requests_path, class: "sidebar-link text-light px-4 py-2 #{active_sidebar_option?({ 'admins/invitation_requests' => ['index'] }) ? 'bg-primary-dark' : ''}" %>
      </li>
    </ul>
  </li>
<% end %>

<li>
  <%= link_to admins_payments_path, class: "sidebar-link text-light px-4 py-2 #{active_sidebar_option?({ 'admins/payments' => ['index'] }) ? 'bg-primary-dark' : ''}" do %>
    <i class="bi bi-credit-card pe-2"></i>
    <%= t('dashboard.payments') %>
  <% end %>
</li>

<li>
  <%= link_to edit_admin_registration_path, class: "sidebar-link text-light px-4 py-2 #{active_sidebar_option?({ 'admins/registrations' => ['edit'], 'admins/admins' => %w[enable_otp disable_otp] }) ? 'bg-primary-dark' : ''}" do %>
    <i class="bi bi-gear-fill pe-2"></i>
    <%= t('dashboard.settings') %>
  <% end %>
</li>


<li>
  <%= button_to destroy_admin_session_path, class: 'sidebar-link text-light px-4 py-2 bg-transparent border-0', method: :delete do %>
    <i class="bi bi-box-arrow-right pe-2"></i>
    <%= t('dashboard.sign_out') %>
  </a>
<% end %>