config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticated :admin, ->(admin) { admin.super_admin? } do
    mount Sidekiq::Web, at: 'admins/sidekiq'
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords',
    confirmations: 'admins/confirmations',
    invitations: 'admins/invitations'
  }

  devise_for :candidates, path: 'candidates', controllers: {
    sessions: 'candidates/sessions',
    registrations: 'candidates/registrations',
    passwords: 'candidates/passwords',
    confirmations: 'candidates/confirmations',
    masquerades: 'admins/masquerades'
  }

  devise_for :recruiters, path: 'recruiters', controllers: {
    sessions: 'recruiters/sessions',
    registrations: 'recruiters/registrations',
    passwords: 'recruiters/passwords',
    confirmations: 'recruiters/confirmations',
    masquerades: 'admins/masquerades'
  }

  devise_scope :admin do
    post 'admins/invitations/resend', to: 'admins/invitations#resend',
                                      as: :resend_admins_invitations,
                                      constraints: { format: :json }
  end

  devise_scope :candidate do
    post '/auth/github' => 'omniauth_callbacks#passthru', as: :candidate_github_omniauth_authorize
    post '/auth/google_oauth2' => 'omniauth_callbacks#passthru', as: :candidate_google_oauth2_omniauth_authorize
    post '/auth/twitter' => 'omniauth_callbacks#passthru', as: :candidate_twitter_omniauth_authorize
  end

  devise_scope :recruiter do
    post '/auth/github' => 'omniauth_callbacks#passthru', as: :recruiter_github_omniauth_authorize
    post '/auth/google_oauth2' => 'omniauth_callbacks#passthru', as: :recruiter_google_oauth2_omniauth_authorize
    post '/auth/twitter' => 'omniauth_callbacks#passthru', as: :recruiter_twitter_omniauth_authorize
  end

  get '/auth/github/callback' => 'omniauth_callbacks#github', as: :github_omniauth_callback
  get '/auth/google_oauth2/callback' => 'omniauth_callbacks#google_oauth2', as: :google_oauth2_omniauth_callback
  get '/auth/twitter/callback' => 'omniauth_callbacks#twitter', as: :twitter_omniauth_callback

  authenticated :admin do
    root 'admins/dashboard#show', as: :admins_authenticated_root
  end

  authenticated :candidate do
    root 'candidates/dashboard#show', as: :candidates_authenticated_root
  end

  authenticated :recruiter do
    root 'recruiters/dashboard#show', as: :recruiters_authenticated_root
  end

  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/about', to: 'pages#home'
  get '/cotizacion', to: 'pages#home'
  post '/contact_form', to: 'contact_form#create'

  namespace :admins do
    get 'dashboard/show'

    resources :admins, only: %i[index]
    resources :candidates, only: %i[index]
    resources :recruiters, only: %i[index]
    resources :payments, only: %i[index]

    resources :invitation_requests, only: %i[index new create] do
      scope constraints: { format: :json } do
        member do
          post :dismiss
          post :ban
        end
      end
    end

    get 'enable_otp', to: 'admins#enable_otp'
    post 'enable_otp_verify', to: 'admins#enable_otp_verify'

    get 'disable_otp', to: 'admins#disable_otp'
    post 'disable_otp_verify', to: 'admins#disable_otp_verify'
  end

  namespace :candidates do
    get 'dashboard/show'

    resources :subscriptions, only: %i[index create] do
      get :prices, on: :collection
      get :billing_portal, on: :collection
    end

    resource :my_resume, only: %i[show update], controller: :my_resume
    resources :education_items, only: %i[create destroy]
    resources :work_experience_items, only: %i[create destroy]
    resources :skill_items, only: %i[create destroy]
    resources :reference_items, only: %i[create destroy]
    resources :external_link_items, only: %i[create destroy]

    resources :job_postings, only: %i[index show]
    resources :postulations, only: :create
  end

  namespace :recruiters do
    get 'dashboard/show'

    resources :job_postings do
      resources :postulations, only: [] do
        post :approve
        post :reject
      end
    end
    resources :candidates, only: %i[index show]
    resources :resumes, only: %i[show]
  end

  resources :stripe_webhooks, only: [:create]
end

app/views/admins/admins/disable_otp.html.erb
<% content_for :top_section do %>
  <h2 class="mb-1"><%= t('dashboard.settings') %></h2>
  <p class="small text-muted mb-0"><%= t('dashboard.settings') %> / <strong><%= t('dashboard.disable_2fa') %></strong></p>
<% end %>

<div class="authentication-page">
  <%= link_to t('general.back'), edit_admin_registration_path, class: 'border-0 btn m-0 mb-3 p-0 text-decoration-underline text-primary' %>

  <%= form_for(current_admin, as: :admin, url: admins_disable_otp_verify_path, html: { method: :post }, data: { turbo: true }) do |f| %>
    <div class="mb-4">
      <%= f.password_field :current_password,
                           autocomplete: 'current-password',
                           class: 'form-control rounded-pill bg-light',
                           placeholder: t('devise.passwords.edit.current_password')
      %>
    </div>

    <div class="mb-4">
      <%= f.text_field :otp_attempt, class: 'form-control rounded-pill bg-light', placeholder: t('devise.passwords.edit.enter_otp') %>
    </div>

    <div class="mb-4 text-center">
      <%= f.submit t('admins.enable_otp.verify_and_disable_2fa'), class: 'btn-submit btn btn-danger border-0 shadow mb-1 w-100 text-light rounded-pill' %>
    </div>
  <% end %>
</div>

app/views/admins/admins/enable_otp.html.erb
<% content_for :top_section do %>
  <h2 class="mb-1"><%= t('dashboard.settings') %></h2>
  <p class="small text-muted mb-0"><%= t('dashboard.settings') %> / <strong><%= t('dashboard.enable_2fa') %></strong></p>
<% end %>

<%= link_to t('general.back'), edit_admin_registration_path, class: 'border-0 btn m-0 mb-3 p-0 text-decoration-underline text-primary' %>

<p class="mb-3"><%= t('admins.enable_otp.scan_qr_code') %></p>

<div class="mb-3 text-center">
  <%= raw RQRCode::QRCode.new(
        @provisioning_uri,
        :svg,
        level: :l,
        unit: 2
      ).as_svg(module_size: 5) %>
</div>

<%= form_tag admins_enable_otp_verify_path, method: :post do %>
  <div class="mb-3">
    <%= text_field_tag :otp_attempt, nil, class: 'form-control rounded-pill bg-light', placeholder: t('admins.enable_otp.enter_one_time_password') %>
  </div>

  <%= submit_tag t('admins.enable_otp.verify_and_enable_2fa'), class: 'btn-submit btn btn-primary border-0 shadow mb-1 w-100 text-light rounded-pill' %>
<% end %>

app/views/admins/admins/enable_otp_show_qr.html.erb
<% content_for :top_section do %>
  <h2 class="mb-1"><%= t('dashboard.settings') %></h2>
  <p class="small text-muted mb-0"><%= t('dashboard.settings') %> / <strong><%= t('dashboard.enable_2fa') %></strong></p>
<% end %>

<%= link_to t('general.back'), edit_admin_registration_path, class: 'border-0 btn m-0 mb-3 p-0 text-decoration-underline text-primary' %>

<p class="mb-3"><%= t('admins.enable_otp_show_qr.scan_qr_code') %></p>

<div class="mb-3 text-center">
  <%= raw RQRCode::QRCode.new(
        @provisioning_uri,
        :svg,
        level: :l,
        unit: 2
      ).as_svg(module_size: 5) %>
</div>

<%= form_tag admins_enable_otp_verify_path, method: :post do %>
  <div class="mb-3">
    <%= text_field_tag :otp_attempt, nil, class: 'form-control rounded-pill bg-light', placeholder: t('admins.enable_otp_show_qr.enter_one_time_password') %>
  </div>

  <%= submit_tag t('admins.enable_otp_show_qr.verify_and_enable_2fa'), class: 'btn-submit btn btn-primary border-0 shadow mb-1 w-100 text-light rounded-pill' %>
<% end %>

app/views/admins/admins/index.html.erb
<% content_for :top_section do %>
  <h2 class="mb-1"><%= t('dashboard.admins') %></h2>
  <p class="small text-muted mb-0"><%= t('dashboard.users') %> / <strong><%= t('dashboard.admins') %></strong></p>
<% end %>

<%= content_tag(:div, '', id: 'admins-admins-container', data: {
  controller: 'admins_admins'
}) %>